version: "3.9"

services:
  nodefrontend:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    env_file:
    - ./frontend/.env.development
    ports:
    - "8090:8090"
    volumes:
    - ./frontend/public:/usr/src/app/public
    - ./server:/usr/src/app/server
    environment:
      NODE_ENV: development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
    - ./frontend/.env.development
    ports:
    - "8060:8060"
    volumes:
    - ./frontend/src:/usr/src/app/src
    environment:
      NODE_ENV: development

  apimock:
    build:
      context: ./api-mock-server
      dockerfile: Dockerfile
    env_file:
      - ./api-mock-server/.env.development
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  ruby:
    build:
      context: ./api-mock-server/scripts
      dockerfile: Dockerfile
    command: bash -c 'ruby ./api-mock-server/scripts/genererOppgaver.rb ./api-mock-server/oppgaver.db'
    working_dir: /usr/app/
    volumes:
      - ./:/usr/app/
