export enum ColumnKeyEnum {
  Type,
  Ytelse,
  RolYtelse,
  Hjemmel,
  RolHjemmel,
  EnhetHjemmel,
  Navn,
  Fnr,
  Age,
  Deadline,
  Medunderskriver,
  Rol,
  FlowStates,
  Open,
  TildelingWithFilter,
  Tildeling,
  Oppgavestyring,
  OppgavestyringNonFilterable,
  Utfall,
  PaaVentTil,
  PaaVentReason,
  Finished,
  Returnert,
  Feilregistrering,
  Feilregistrert,
  Saksnummer,
  RolTildeling,
  RelevantOppgaver,
}

export const TABLE_HEADERS: Record<ColumnKeyEnum, string | null> = {
  [ColumnKeyEnum.Type]: 'Type',
  [ColumnKeyEnum.Ytelse]: 'Ytelse',
  [ColumnKeyEnum.RolYtelse]: 'Ytelse',
  [ColumnKeyEnum.Hjemmel]: 'Hjemmel',
  [ColumnKeyEnum.RolHjemmel]: 'Hjemmel',
  [ColumnKeyEnum.EnhetHjemmel]: 'Hjemmel',
  [ColumnKeyEnum.Navn]: 'Navn',
  [ColumnKeyEnum.Fnr]: 'Fnr.',
  [ColumnKeyEnum.Age]: 'Alder',
  [ColumnKeyEnum.Deadline]: 'Frist',
  [ColumnKeyEnum.Medunderskriver]: 'Medunderskriver',
  [ColumnKeyEnum.Rol]: 'Rådgivende overlege',
  [ColumnKeyEnum.FlowStates]: null,
  [ColumnKeyEnum.Open]: null,
  [ColumnKeyEnum.Tildeling]: 'Tildeling',
  [ColumnKeyEnum.TildelingWithFilter]: 'Tildeling',
  [ColumnKeyEnum.Oppgavestyring]: 'Tildeling',
  [ColumnKeyEnum.OppgavestyringNonFilterable]: 'Tildeling',
  [ColumnKeyEnum.Utfall]: 'Utfall',
  [ColumnKeyEnum.PaaVentTil]: 'På vent til',
  [ColumnKeyEnum.PaaVentReason]: 'Årsak',
  [ColumnKeyEnum.Finished]: 'Fullført',
  [ColumnKeyEnum.Returnert]: 'Returnert',
  [ColumnKeyEnum.Feilregistrering]: null,
  [ColumnKeyEnum.Feilregistrert]: 'Tidspunkt for feilregistrering',
  [ColumnKeyEnum.Saksnummer]: 'Saksnummer',
  [ColumnKeyEnum.RolTildeling]: 'Tildeling',
  [ColumnKeyEnum.RelevantOppgaver]: null,
};
