export enum TemplateIdEnum {
  NOTAT = 'notat',
  GENERELT_BREV = 'generelt_brev',
  ANKEVEDTAK = 'ankevedtak',
  KLAGEVEDTAK_V1 = 'klagevedtak',
  KLAGEVEDTAK_V2 = 'klagevedtak-v2',
  ROL_QUESTIONS = 'rol-questions',
  ROL_ANSWERS = 'rol-answers',
  ROL_TILSVARSBREV = 'rol-tilsvarsbrev',
  OVERSENDELSESBREV = 'oversendelsesbrev',
  ORIENTERING_OM_TILSVAR = 'orientering-om-tilsvar',
  BEHANDLING_ETTER_TR_OPPHEVET_VEDTAK = 'behandling-etter-tr-opphevet',
  OMGJØRINGSKRAVVEDTAK = 'omgjøringskravvedtak',
  FORENKLET_BESLUTNING_OM_IKKE_Å_OMGJØRE = 'forenklet-beslutning-om-ikke-å-omgjøre',
  SVAR_PÅ_INNSYNSBEGJÆRING = 'svar-på-innsynsbegjæring',
  VARSEL_OM_OMGJØRING_TIL_UGUNST_TEMPLATE = 'varsel-om-omgjøring-til-ugunst',
  EKSPEDISJONSBREV_TIL_TRYGDERETTEN = 'ekspedisjonsbrev-til-trygderetten',
  ETTERSENDING_TIL_TRYGDERETTEN = 'ettersending-til-trygderetten',
  GJENOPPTAKSBEGJÆRING_VEDTAK = 'gjenopptakelsesbegjæring-vedtak',
  GJENOPPTAKSBEGJÆRING_TILSVARSBREV_MED_OVERSENDELSESBREV = 'gjenopptakelsesbegjæring-tilsvarsbrev-med-oversendelsesbrev',
  GJENOPPTAKSBEGJÆRING_EKSPEDISJONSBREV_TIL_TR = 'gjenopptakelsesbegjæring-ekspedisjonsbrev-til-tr',
  GJENOPPTAKSBEGJÆRING_ORIENTERING_OM_TILSVAR_DIREKTE_TIL_TR = 'gjenopptakelsesbegjæring-orientering-om-tilsvar-direkte-til-tr',
  GJENOPPTAKSBEGJÆRING_ETTERSENDING_TIL_TR = 'gjenopptakelsesbegjæring-ettersending-til-tr',
}
