import { DocumentTypeEnum, type IMainDocument } from '@app/types/documents/documents';

/** Matches two journalfoerte documents on their journalpostId, dokumentInfoId and parentId. Not the property `id`, which is generated by Kabal.
 * Useful in DUA list where we want to match documents that are the same, but have different IDs, and can be duplicated under different parents.
 */
export const areJournalfoertDocumentsEqual = (a: IMainDocument, b: IMainDocument): boolean =>
  a.type === DocumentTypeEnum.JOURNALFOERT &&
  b.type === DocumentTypeEnum.JOURNALFOERT &&
  a.journalfoertDokumentReference.dokumentInfoId === b.journalfoertDokumentReference.dokumentInfoId &&
  a.journalfoertDokumentReference.journalpostId === b.journalfoertDokumentReference.journalpostId &&
  a.parentId === b.parentId;
