name: 'Deploy to dev'
description: 'Deploy to dev'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to dev
      uses: nais/deploy/actions/deploy@v1
      env:
        APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
        CLUSTER: dev-gcp
        TEAM: klage
        VAR: image=${{ steps.docker-push.outputs.image }}
        VARS: nais/dev.yaml
        RESOURCE: nais/nais.yaml
        IMAGE: ${{ steps.docker-push.outputs.image }}
      timeout-minutes: 5
