import { ANKEVEDTAK_TEMPLATE } from '@app/plate/templates/ankevedtak';
import { KLAGEVEDTAK_TEMPLATE } from '@app/plate/templates/klagevedtak';
import { ORIENTERING_OM_TILSVAR_TEMPLATE } from '@app/plate/templates/orientering-om-tilsvar-direkte-til-trygderetten';
import { OVERSENDELSESBREV_TEMPLATE } from '@app/plate/templates/oversendelsesbrev';
import {
  GENERELT_BREV_TEMPLATE,
  NOTAT_TEMPLATE,
  ROL_ANSWERS_TEMPLATE,
  ROL_QUESTIONS_TEMPLATE,
  ROL_TILSVARSBREV_TEMPLATE,
} from '@app/plate/templates/simple-templates';

export const TEMPLATE_MAP = {
  [GENERELT_BREV_TEMPLATE.templateId]: GENERELT_BREV_TEMPLATE,
  [NOTAT_TEMPLATE.templateId]: NOTAT_TEMPLATE,
  [KLAGEVEDTAK_TEMPLATE.templateId]: KLAGEVEDTAK_TEMPLATE,
  [ANKEVEDTAK_TEMPLATE.templateId]: ANKEVEDTAK_TEMPLATE,
  [OVERSENDELSESBREV_TEMPLATE.templateId]: OVERSENDELSESBREV_TEMPLATE,
  [ROL_QUESTIONS_TEMPLATE.templateId]: ROL_QUESTIONS_TEMPLATE,
  [ROL_ANSWERS_TEMPLATE.templateId]: ROL_ANSWERS_TEMPLATE,
  [ROL_TILSVARSBREV_TEMPLATE.templateId]: ROL_TILSVARSBREV_TEMPLATE,
  [ORIENTERING_OM_TILSVAR_TEMPLATE.templateId]: ORIENTERING_OM_TILSVAR_TEMPLATE,
};

export const TEMPLATES = Object.values(TEMPLATE_MAP);

export const KLAGE_TEMPLATES = [
  GENERELT_BREV_TEMPLATE,
  NOTAT_TEMPLATE,
  KLAGEVEDTAK_TEMPLATE,
  ROL_QUESTIONS_TEMPLATE,
  ROL_TILSVARSBREV_TEMPLATE,
];

export const ANKE_TEMPLATES = [
  GENERELT_BREV_TEMPLATE,
  NOTAT_TEMPLATE,
  ANKEVEDTAK_TEMPLATE,
  OVERSENDELSESBREV_TEMPLATE,
  ORIENTERING_OM_TILSVAR_TEMPLATE,
  ROL_QUESTIONS_TEMPLATE,
  ROL_TILSVARSBREV_TEMPLATE,
];

export const ANKE_I_TRYGDERETTEN_TEMPLATES = [GENERELT_BREV_TEMPLATE, NOTAT_TEMPLATE, ORIENTERING_OM_TILSVAR_TEMPLATE];
