import { ENVIRONMENT } from '@app/environment';
import { ANKEVEDTAK_TEMPLATE } from './ankevedtak';
import { KLAGEVEDTAK_TEMPLATE } from './klagevedtak';
import {
  GENERELT_BREV_TEMPLATE,
  NOTAT_TEMPLATE,
  ROL_ANSWERS_TEMPLATE,
  ROL_QUESTIONS_TEMPLATE,
} from './simple-templates';

// TODO: Remove ternary when ROL is done.
export const TEMPLATES = ENVIRONMENT.isProduction
  ? [GENERELT_BREV_TEMPLATE, NOTAT_TEMPLATE, KLAGEVEDTAK_TEMPLATE, ANKEVEDTAK_TEMPLATE]
  : [
      GENERELT_BREV_TEMPLATE,
      NOTAT_TEMPLATE,
      KLAGEVEDTAK_TEMPLATE,
      ANKEVEDTAK_TEMPLATE,
      ROL_QUESTIONS_TEMPLATE,
      ROL_ANSWERS_TEMPLATE,
    ];

// TODO: Remove ternary when ROL is done.
export const KLAGE_TEMPLATES = ENVIRONMENT.isProduction
  ? [GENERELT_BREV_TEMPLATE, NOTAT_TEMPLATE, KLAGEVEDTAK_TEMPLATE]
  : [GENERELT_BREV_TEMPLATE, NOTAT_TEMPLATE, KLAGEVEDTAK_TEMPLATE, ROL_QUESTIONS_TEMPLATE];

// TODO: Remove ternary when ROL is done.
export const ANKE_TEMPLATES = ENVIRONMENT.isProduction
  ? [GENERELT_BREV_TEMPLATE, NOTAT_TEMPLATE, ANKEVEDTAK_TEMPLATE]
  : [GENERELT_BREV_TEMPLATE, NOTAT_TEMPLATE, ANKEVEDTAK_TEMPLATE, ROL_QUESTIONS_TEMPLATE];

export const ANKE_I_TRYGDERETTEN_TEMPLATES = [GENERELT_BREV_TEMPLATE, NOTAT_TEMPLATE];

export const TEMPLATE_IDS = TEMPLATES.map((t) => t.templateId);
