apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: klage-oppgave
  namespace: klage
  labels:
    team: klage
spec:
  image: {{image}}
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no

  accessPolicy:
    outbound:
      rules:
        - application: klage-oppgave-api
      external:
        - host: login.microsoftonline.com
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
