apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kabal-frontend
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
spec:
  image: {{image}}
  replicas:
    min: 2
    max: 3
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      claims:
        groups:
        {{#each roles as |role|}}
          - id: {{role}}
        {{/each}}
        extra:
          - NAVident
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths: 
        - /assets/*
        - /*.js.map
        - /*.js
        - /*.html
        - /*.txt
        - /*.css
  prometheus:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: kabal-e2e-tests
    outbound:
      rules:
        - application: klage-redis-fe
        - application: kabal-api
        - application: kabal-smart-editor-api
        - application: kabal-json-to-pdf
        - application: kabal-search
        - application: kaka-api
        - application: kabal-innstillinger
        - application: klage-kodeverk-api
        - application: kabal-text-templates
      external:
        - host: login.microsoftonline.com
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: kabal-session-key
    - secret: slack-url
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  observability:
    tracing:
      enabled: true
