---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: klage
  name: klage-redis-fe
  namespace: klage
spec:
  image: redis:latest
  port: 6379
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1 # More replicas doesn't sync
  resources: # you need to monitor the resource usage yourself
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy: # for GCP
    inbound:
      rules:
        - application: kabal-frontend
