name: 'Build and test'
description: 'Build and test'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install frontend dependencies
      shell: bash
      run: |
        cd frontend
        npm ci
    - name: Build frontend
      shell: bash
      env:
        VERSION: ${{ github.sha }}
      run: |
        cd frontend
        npm run build
    - name: Test frontend
      shell: bash
      run: |
        cd frontend
        npm test
    - name: Install server dependencies
      shell: bash
      run: |
        cd server
        npm ci
    - name: Build server
      shell: bash
      run: |
        cd server
        npm run build
    - name: Test server
      shell: bash
      run: |
        cd server
        npm test
