name: Bygg manuelt

on:
  workflow_dispatch:
  push:
    branches:
      - dockercompose

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/klage-oppgave:${{ github.sha }}
  LATEST: docker.pkg.github.com/${{ github.repository }}/klage-oppgave:latest  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        run: |
          cd frontend
          npm i
      - name: Test
        run: |
          cd frontend
          npm test
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SESSION_KEY: ${{ secrets.klage-session-key }}
        run: |
          cat Dockerfile
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
          docker build --tag ${LATEST} .
          docker push ${LATEST}
  deploypreprod:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: nais/deploy/actions/deploy@master
        env:
          SESSION_KEY: ${{ secrets.klage-session-key }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          VARS: nais/vars.yaml
