name: Kjør akseptansetest

on:
  workflow_dispatch:
  push:
    branches:
      - e2e

jobs:
  acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: navikt/klage-oppgave
      - uses: nais/deploy/actions/deploy@v1
        name: Run tests
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          IMAGE: docker.pkg.github.com/navikt/klage-oppgave-e2e:e9cc8959c42964bd9392c3341319039f42f73557
          CLUSTER: dev-gcp
          VARS: nais/jobvars.yml
          RESOURCE: nais/e2ejob.yml
          TEAM: klage
          NAMESPACE: klage
        timeout-minutes: 5