name: Kjør akseptansetest

on:
  workflow_dispatch:
  push:
    branches:
      - e2e

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/klage-oppgave:${{ github.sha }}
  LATEST: docker.pkg.github.com/${{ github.repository }}/klage-oppgave:latest  
jobs:
  acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - uses: nais/deploy/actions/deploy@v1
        name: Run tests
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          IMAGE: docker.pkg.github.com/navikt/klage-oppgave-e2e/klage-oppgave-e2e:latest
          CLUSTER: klage
          VAR: app=klage-oppgave-e2e
          RESOURCE: nais/e2ejob.yaml
        timeout-minutes: 5