name: Kjør akseptansetest

on:
  workflow_dispatch:
  push:
    branches:
      - e2e

jobs:
  acceptance-tests:
    name: Run acceptance tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: navikt/klage-oppgave
          token: "
      - uses: nais/deploy/actions/deploy@v1
        name: Run tests
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_API_KEY }}
          IMAGE: docker.pkg.github.com/navikt/klage-oppgave-e2e
          CLUSTER: dev-gcp
          VAR: app=medlemskap-oppslag
          RESOURCE: nais/e2ejob.yml
        timeout-minutes: 5