name: E2E tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: navikt/kabal
      - name: Set UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1.1
      - name: Run E2E tests
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          VAR: app=kabal-e2e-tests,jobname=kabal-e2e-tests-job-${{ steps.generate-uuid.outputs.uuid }}
          TEAM: klage
          RESOURCE: nais/e2ejob.yaml
        timeout-minutes: 5
