name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - main

jobs:
  deploytodev:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: actions/build-and-test

      - name: Build and publish Docker image
        uses: actions/docker

      - name: Deploy to dev
        uses: actions/deploy-to-dev
  
  e2etest:
    name: E2E-test av deploy
    uses: ./.github/workflows/e2e.yaml
    needs: deploytodev
  
  deployprod:
    name: Deploy to prod-gcp
    needs: e2etest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-to-prod
        name: Deploy to prod
