name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - main

jobs:
  deploy_to_dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy.yaml
    with:
      env: dev
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  
  deploy_to_prod:
    name: Deploy to prod
    needs: deploy_to_dev
    uses: ./.github/workflows/deploy.yaml
    with:
      env: prod
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
