name: Deploy (dev -> e2e -> prod)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yaml
    with:
      deploy_to_prod: true
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
