name: Manual deploy to production

on:
  workflow_dispatch:

jobs:
  deployprod:
    name: Deploy to prod-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: actions/build-and-test

      - name: Build and publish Docker image
        uses: actions/docker

      - name: Deploy to prod
        uses: actions/deploy-to-prod
