name: Manual deploy to dev

on:
  workflow_dispatch:

jobs:
  deploytodev:
    runs-on: ubuntu-latest
    steps:
      - name: Build and test
        uses: actions/build-and-test

      - name: Build and publish Docker image
        uses: actions/docker

      - name: Deploy to dev
        uses: actions/deploy-to-dev
  e2etest:
    name: E2E-test av deploy
    uses: ./.github/workflows/e2e.yaml
    needs: deploytodev
